#!/bin/bash
#SBATCH --mem=16g
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=64
#SBATCH --partition=cpu
#SBATCH --account=mzu-delta-cpu
#SBATCH --job-name=myjobtest
#SBATCH --time=00:10:00      # hh:mm:ss for the job
#SBATCH --constraint="scratch"

module load openmpi-5.0_beta/5.0.0rc9
echo "job is starting p4, process cnt per node=2, node=2 on `hostname`"
srun --mpi=pmi2 -n 4 ./pingack +setcpuaffinity +pemap 0-31