#!/bin/bash
#SBATCH --mem=16g
#SBATCH --nodes=2
#SBATCH --output=smp-procpn01-n2-%j.out
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=128
#SBATCH --partition=cpu
#SBATCH --account=mzu-delta-cpu
#SBATCH --job-name=myjobtest
#SBATCH --time=00:05:00
#SBATCH --constraint="scratch"

module load openmpi-5.0_beta/5.0.0rc9
echo "job is starting +p254, ppn 127, n2, pemap 0-252 + commap 127-127"
srun --mpi=pmi2 -n 2 pingack_smp ++ppn 127 +pemap 0-126 +commap 127-127
