#!/bin/bash
#SBATCH --mem=16g
#SBATCH --nodes=2
#SBATCH --output=smp-procpn16-n2-%j.out
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=8
#SBATCH --partition=cpu
#SBATCH --account=mzu-delta-cpu
#SBATCH --job-name=myjobtest
#SBATCH --time=00:05:00
#SBATCH --constraint="scratch"

module load openmpi-5.0_beta/5.0.0rc9
echo "job is starting +p14, ppn 07, n2, pemap 0-12 + commap 7-127"
srun --mpi=pmi2 -n 32 pingack_smp ++ppn 7 +pemap 0-111 +commap 112-127
