#!/bin/bash
#SBATCH --mem=16g
#SBATCH --nodes=2
#SBATCH --output=smp-procpn08-n2-%j.out
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=16
#SBATCH --partition=cpu
#SBATCH --account=mzu-delta-cpu
#SBATCH --job-name=myjobtest
#SBATCH --time=00:05:00
#SBATCH --constraint="scratch"

module load openmpi-5.0_beta/5.0.0rc9
echo "job is starting +p30, ppn 15, n2, pemap 0-28 + commap 15-127"
srun --mpi=pmi2 -n 16 pingack_smp ++ppn 15 +pemap 0-119 +commap 120-127
