#!/bin/bash
#SBATCH --mem=16g
#SBATCH --nodes=2
#SBATCH --output=smp-procpn02-n2-%j.out
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=64
#SBATCH --partition=cpu
#SBATCH --account=mzu-delta-cpu
#SBATCH --job-name=myjobtest
#SBATCH --time=00:05:00
#SBATCH --constraint="scratch"

module load openmpi-5.0_beta/5.0.0rc9
echo "job is starting +p126, ppn 63, n2, pemap 0-124 + commap 63-127"
srun --mpi=pmi2 -n 4 pingack_smp ++ppn 63 +pemap 0-125 +commap 126-127
